### ISSUE TITLE
Use `set -e` in script that deploy docs in GitHub Action

### ISSUE THREAD

**Issue by santisoler** [fatiando/community#166]
**Description:**

We have a custom bash script in our GitHub Actions that deploys the built docs to the `gh-pages`. By default, if one of the commands in the script fails, the script continues running. Moreover, even if one of the commands fails, the script still exists with code 0. That means that the  job in Actions will pass even if one of the commands (like pushing the built docs) fail.

We should use `set -e` when running scripts in Actions. We could also explore setting it globally, by passing arguments to `bash` under `defaults` section.

**Apply to:**

- [ ] [boule](https://github.com/fatiando/boule)
- [ ] [harmonica](https://github.com/fatiando/harmonica)
- [ ] [pooch](https://github.com/fatiando/pooch)
- [ ] [verde](https://github.com/fatiando/verde)
- [ ] [ensaio](https://github.com/fatiando/ensaio)
- [ ] [choclo](https://github.com/fatiando/choclo)
- [ ] [magali](https://github.com/fatiando/magali)
- [ ] [dependente](https://github.com/fatiando/dependente)
- [ ] [burocrata](https://github.com/fatiando/burocrata)
- [ ] [website](https://github.com/fatiando/website)
- [ ] [tutorials](https://github.com/fatiando/tutorials)
- [ ] [community](https://github.com/fatiando/community)
- [ ] [.github](https://github.com/fatiando/.github)

**Further instructions:**

* Start by opening Pull Requests on each repository listed above.
* Optionally, we can open Issues on each repository if further discussion specific to that repository is needed.
* Mention this Issue on every Issue or Pull Request opened on each opened: `Related to fatiando/community#XX`
* Check-off the repository on the list above once the Pull Request is merged.
* Close this issue when all items are checked-off.

**We want your help!**

We know that maintenance tasks are very demanding, so we don't expect a single person to tackle this issue by themselves. Any help is very welcomed, so please comment below that you want to take care of the changes on any repository and we will assign it to you.

**Comment by leouieda** [comment]
We can add `-e` globally by changing these lines at the top:

```yaml
defaults:
  run:
    # The -l {0} is necessary for conda environments to be activated
    # But this breaks on MacOS if using actions/setup-python:
    # https://github.com/actions/setup-python/issues/132
    # -e makes sure builds fail if any command fails
    shell: bash -e -l {0}
```

The `-l` is only set for Actions that need conda.

**Comment by santisoler** [comment]
As @leouieda mentioned in Mattermost, by default GitHub uses `-e`, but by manually redefining the shell in the `default` section, we are overriding those defaults.

I think we should maintain the same [defaults that GitHub uses](https://github.com/actions/setup-python/issues/132) by setting:

```yaml
defaults:
  run:
    # The -l {0} is necessary for conda environments to be activated
    # But this breaks on MacOS if using actions/setup-python:
    # https://github.com/actions/setup-python/issues/132
    # -e makes sure builds fail if any command fails
    shell: bash -e -o pipefail -l {0}
```
